---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ambassador-certs
  namespace: default
spec:
  secretName: tls-cert
  issuerRef:
    name: pp-prod
    kind: ClusterIssuer
  dnsNames:
    - premierpredictor.uk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - premierpredictor.uk