---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: pp-prod
spec:
  acme:
    email: shepapps4@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: pp-prod
    solvers:
      - http01:
          ingress:
            class: nginx
        selector: {}