apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: premierpredictor-deployment
spec:
  selector:
    matchLabels:
      app: premierpredictor-app
  template:
    metadata:
      labels:
        app: premierpredictor-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: premierpredictor-app
          image: premierpredictor
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: server
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: apiKey
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: apiUrl
            - name: API_URL_COMMENTARY
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: apiUrlCommentary
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: dbUrl
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: dbUser
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: dbPassword
            - name: MONGO_SCHEME
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbScheme
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbUser
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbPassword
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbHost
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: jwtSecret
            - name: MONGO_PORT
              value: ""
            - name: SEND_GRIP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: sendGridApiKey
            - name: JAVA_OPTS
              value: -Xmx125m -Xms125m -Xss256k -XX:+UseCompressedOops -XX:+UseContainerSupport -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark
          readinessProbe:
            httpGet:
              path: /_health
              port: 8080
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /_health
              port: 8080
            initialDelaySeconds: 60
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "600Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: premierpredictor-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: core_mapping
      prefix: /
      service: premierpredictor-service:8080
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: premierpredictor-app
  type: ClusterIP

#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  annotations:
##    kubernetes.io/ingress.allow-http: "false"
##    ingress.kubernetes.io/force-ssl-redirect: "true"
#  name: app-ingress
#  namespace: default
#spec:
#  tls:
#    - hosts:
#      - app.premierpredictor.uk
#    - secretName: pp-secret
#  rules:
#    - host: app.premierpredictor.uk
#      http:
#        paths:
#          - backend:
#              serviceName: premierpredictor-service
#              servicePort: 8080
#            path: /
