apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fixtureservice-app
  namespace: default
  labels:
    k8s-app: fixtureservice-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: fixtureservice-app
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: fixtureservice-app
          image: fixtureservice
          ports:
            - name: grpc
              containerPort: 3006
          env:
            - name: PORT
              value: "3006"
            - name: HTTP_PORT
              value: "8086"
            - name: AUTH_ADDR
              value: "authservice:3001"
            - name: MONGO_SCHEME
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbScheme
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbUser
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbPassword
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbHost
          readinessProbe:
            httpGet:
              path: /health
              port: 8086
          livenessProbe:
            httpGet:
              path: /health
              port: 8086
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
 apiVersion: v1
 kind: Service
 metadata:
   name: fixtureservice
   namespace: default
 spec:
   selector:
     k8s-app: fixtureservice-app
   ports:
     - port: 3006
       targetPort: 3006
       name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: fixtureservice-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: fixture_mapping
      prefix: /fixtures/
      service: fixtureservice-service:8086
spec:
  ports:
    - port: 8086
      targetPort: 8086
      name: http
  selector:
    k8s-app: fixtureservice-app
  type: ClusterIP
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  annotations:
##    kubernetes.io/ingress.allow-http: "false"
##    ingress.kubernetes.io/force-ssl-redirect: "true"
#  name: fixture-ingress
#  namespace: default
#spec:
#  tls:
#    - hosts:
#      - fixture.premierpredictor.uk
#    - secretName: pp-secret
#  rules:
#    - host: fixture.premierpredictor.uk
#      http:
#        paths:
#          - backend:
#              serviceName: fixtureservice-service
#              servicePort: 8086
#            path: /
