apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayservice-app
  namespace: default
  labels:
    k8s-app: gatewayservice-app
spec:
  selector:
    matchLabels:
      k8s-app: gatewayservice-app
  template:
    metadata:
      labels:
        k8s-app: gatewayservice-app
    spec:
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
        - name: github-packages-secret
      containers:
        - name: gatewayservice-app
          image: docker.pkg.github.com/cshep4/premier-predictor-microservices/gatewayservice:master_736db453
          ports:
            - name: http
              containerPort: 4000
          env:
            - name: AUTH_ADDR
              value: "kauthservice:3001"
            - name: FIXTURE_ADDR
              value: "fixtureservice:3006"
            - name: PREDICTION_ADDR
              value: "predictionservice:3007"
            - name: LIVE_MATCH_ADDR
              value: "livematchservice:3008"
            - name: LEAGUE_ADDR
              value: "leagueservice:3009"
            - name: USER_ADDR
              value: "userservice:3005"
          readinessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 4000
            initialDelaySeconds: 120
          livenessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 4000
            initialDelaySeconds: 120
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: gatewayservice-mapping
spec:
  prefix: /gateway/
  service: gatewayservice-service:4000
  allow_upgrade:
    - websocket
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayservice-service
spec:
  ports:
    - port: 4000
      targetPort: 4000
      name: http
  selector:
    k8s-app: gatewayservice-app
  type: ClusterIP
