apiVersion: apps/v1
kind: Deployment
metadata:
  name: kauthservice-app
  namespace: default
  labels:
    k8s-app: kauthservice-app
spec:
  template:
    metadata:
      labels:
        k8s-app: kauthservice-app
    spec:
      selector:
        matchLabels:
          k8s-app: kauthservice-app
      terminationGracePeriodSeconds: 5
      containers:
        - name: kauthservice-app
          image: docker.pkg.github.com/cshep4/premier-predictor-microservices/kauthservice:v1.0.0
          ports:
            - name: grpc
              containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: HTTP_PORT
              value: "8081"
            - name: USER_ADDR
              value: "userservice"
            - name: USER_PORT
              value: "3005"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: jwtSecret
            - name: EMAIL_URL
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: emailUrl
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kauthservice
  namespace: default
spec:
  selector:
    k8s-app: kauthservice-app
  ports:
    - port: 3001
      targetPort: 3001
      name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: kauthservice-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: auth_mapping
      prefix: /auth/
      service: kauthservice-service:8081
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  selector:
    k8s-app: kauthservice-app
  type: ClusterIP
