apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: livematchservice-app
  namespace: default
  labels:
    k8s-app: livematchservice-app
spec:
  template:
    metadata:
      labels:
        k8s-app: livematchservice-app
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: livematchservice-app
          image: livematchservice
          ports:
            - containerPort: 3008
              name: grpc
          env:
            - name: PORT
              value: "3008"
            - name: HTTP_PORT
              value: "8088"
            - name: AUTH_ADDR
              value: "authservice:3001"
            - name: PREDICTION_ADDR
              value: "predictionservice:3007"
            - name: MONGO_SCHEME
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbScheme
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbUser
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbPassword
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbHost
          readinessProbe:
            httpGet:
              path: /health
              port: 8088
          livenessProbe:
            httpGet:
              path: /health
              port: 8088
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: livematchservice
  namespace: default
spec:
  selector:
    k8s-app: livematchservice-app
  ports:
    - port: 3008
      targetPort: 3008
      name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: livematchservice-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: livematch_mapping
      prefix: /live/
      service: livematchservice-service:8088
spec:
  ports:
    - port: 8088
      targetPort: 8088
      name: https
  selector:
    k8s-app: livematchservice-app
  type: ClusterIP