apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-app
  namespace: default
  labels:
    k8s-app: userservice-app
spec:
  selector:
    matchLabels:
      k8s-app: userservice-app
  template:
    metadata:
      labels:
        k8s-app: userservice-app
    spec:
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
        - name: github-packages-secret
      containers:
        - name: userservice-app
          image: docker.pkg.github.com/cshep4/premier-predictor-microservices/userservice:v1.0.1
          ports:
            - containerPort: 3005
              name: grpc
          env:
            - name: PORT
              value: "3005"
            - name: HTTP_PORT
              value: "8085"
            - name: AUTH_ADDR
              value: "kauthservice:3001"
            - name: MONGO_SCHEME
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbScheme
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbUser
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbPassword
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: dbHost
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: awsAccessKey
            - name: AWS_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: awsAccountId
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: pp-secrets
                  key: awsSecretKey
          readinessProbe:
            httpGet:
              path: /health
              port: 8085
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: default
spec:
  selector:
    k8s-app: userservice-app
  ports:
    - port: 3005
      targetPort: 3005
      name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: userservice-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: user_mapping
      prefix: /user/
      service: userservice-service:8085
spec:
  ports:
    - port: 8085
      targetPort: 8085
      name: http
  selector:
    k8s-app: userservice-app
  type: ClusterIP
