name: Build-Package-LiveMatchService

on:
  push:
    tags-ignore:
      - 'v*.*.*'
    paths:
      - 'src/livematchservice/**'
      - '.github/workflows/build-livematchservice.yml'

env:
  DOCKER_RGISTRY: docker.pkg.github.com/cshep4/premier-predictor-microservices
  GONOSUMDB: github.com/cshep4
  GOPRIVATE: github.com/cshep4

jobs:
  build-and-publish-latest:
    name: Build and Push LiveMatchService
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        run: |
          docker login docker.pkg.github.com -u cshep4 -p ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'

      - name: Install Dependencies
        run: |
          go version
          GO111MODULE=on go get github.com/golang/mock/mockgen@v1.4.4

      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/cshep4".insteadOf "https://github.com/cshep4"

      - name: Build
        run: |
          cd src/livematchservice
          go generate ./...
          go mod vendor
          docker build \
            -t ${{ env.DOCKER_RGISTRY }}/livematchservice:latest \
            -t ${{ env.DOCKER_RGISTRY }}/livematchservice:$(echo ${GITHUB_SHA} | cut -c1-8) \
            -t ${{ env.DOCKER_RGISTRY }}/livematchservice:${GITHUB_REF##*/}_$(echo ${GITHUB_SHA} | cut -c1-8) \
            .

      - name: Push
        run: |
          docker push ${{ env.DOCKER_RGISTRY }}/livematchservice
