name: Build-Package-App

on:
  push:
    paths:
      - 'src/app/**'
      - '.github/workflows/build-app.yml'

jobs:
  test:
    name: Test App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      - name: Get flutter dependencies
        working-directory: src/app
        run: flutter pub get

      - name: Check for formatting issues in the code
        working-directory: src/app
        run: flutter format --set-exit-if-changed .

      - name: Statically analyze Dart code
        working-directory: src/app
        run: flutter analyze .

      - name: Run tests
        working-directory: src/app
        run: flutter test

  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      - name: Get flutter dependencies
        working-directory: src/app
        run: flutter pub get

      - name: Build
        working-directory: src/app
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: apk-build
          path: src/app/build/app/outputs/apk/release

  build_ios:
    name: Build Flutter (iOS)
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      - name: Get flutter dependencies
        working-directory: src/app
        run: flutter pub get

      - name: Clean
        working-directory: src/app
        run: flutter clean

      - name: Build
        working-directory: src/app
        run: flutter build ios --release --no-codesign

      - name: Upload iPA
        uses: actions/upload-artifact@master
        with:
          name: ios-build
          path: src/app/build/ios/iphoneos