name: Deploy-Service

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image Tag
        required: true
      service:
        description: Service Name
        required: true

env:
  DOCKER_RGISTRY: docker.pkg.github.com/cshep4/premier-predictor-microservices

jobs:
  deploy-service:
    name: Deploy Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find and Replace
        uses: bejoistic/str-replace@master
        with:
          find: "image: ${{ env.DOCKER_RGISTRY }}/${{ github.event.inputs.service }}:[^\n]*"
          replace: "image: ${{ env.DOCKER_RGISTRY }}/${{ github.event.inputs.service }}:${{ github.event.inputs.tag }}"
          include: "kubernetes-manifests/"

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # use account 'github-actions[bot]' to set the git config

          git add -A
          git commit -m "deploy ${{ github.event.inputs.service }} ${{ github.event.inputs.tag }}"
          git push